version: '3.8'
services:
  tableplus:
    build: .
    image: tableplus-container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
